### ISSUE TITLE
Return empty array if input is empty array

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [selrond/knit#1]
https://github.com/selrond/knit/blob/a3bd9a3904694a71a219e8f24dd65271e2d3cd3d/src/index.js#L7-L9

Idk about other use cases, but to me, it is more useful to have an empty array returned compared to having an error thrown. 

The `Array.prototype.join()` method also doesn't throw an error, it returns an empty string if the array is empty:

```js
[].join(' + ')
''
```

**Comment by selrond** [comment]
@ChocolateLoverRaj yep, you’re right. Wanna open a PR?

**Comment by ChocolateLoverRaj** [comment]
@selrond I will

**Comment by selrond** [comment]
@ChocolateLoverRaj out of curiosity—do you use this package? If yes, what kind of project do you use it on?

**Comment by ChocolateLoverRaj** [comment]
> @ChocolateLoverRaj out of curiosity—do you use this package? If yes, what kind of project do you use it on?

I am using this package here: https://github.com/ChocolateLoverRaj/ezc/blob/777fd637bba3d711b50a72ee8d24b80ca0294858/lib/core/unparseNode/unparseFunction.ts#L60-L77

I haven't added documentation to [ezc](https://github.com/ChocolateLoverRaj/ezc) about what it is yet but basically how I'm using this package is to turn AST nodes into an array of tokens in a programming language that I'm making.

**Comment by selrond** [comment]
nice! How did you find it?

**Comment by ChocolateLoverRaj** [comment]
> nice! How did you find it?

I was searching for a package that could insert a value between array elements on https://npms.io
